before_script:
  - docker info

build_backend_image:
  script:
    - docker build -t backend backend/Dockerfile
    - docker run backend python --version

build_frontend:
  script:
    - docker build -t frontend app-vendedor/Dockerfile
    - docker run frontend yarn test
    - docker run frontend scripts/deploy.sh
