version: "3.7"

services:
  db:
    image: postgres:12.2
    container_name: backoffice_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres

  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - backend:latest
    image: backend:latest
    ports:
      - "5000:5000"
    hostname: backoffice
    networks:
      default:
        aliases:
          - backoffice
    environment:
      - FLASK_ENV=development
    container_name: backoffice
    command: flask run --host 0.0.0.0 --port 5000
    tty: true
    stdin_open: true
    volumes:
      - .:/home/docker/code
    links:
      - db:db
    depends_on:
      - db
