"""Adiciona Franquia

Revision ID: 3d2ef1bb346e
Revises: c64c49f761cd
Create Date: 2020-11-01 19:27:08.797217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2ef1bb346e'
down_revision = 'c64c49f761cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franquia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(length=19), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_franquia_eid'), 'franquia', ['eid'], unique=True)
    op.add_column('usuario', sa.Column('franquia_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'franquia', ['franquia_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'franquia_id')
    op.drop_index(op.f('ix_franquia_eid'), table_name='franquia')
    op.drop_table('franquia')
    # ### end Alembic commands ###
