"""pedido.status -> pedido.state

Revision ID: 3f81108da8a4
Revises: c64c49f761cd
Create Date: 2020-05-02 14:32:55.081867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f81108da8a4'
down_revision = 'c64c49f761cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('state', sa.String(length=255), nullable=True))
    op.drop_column('pedido', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pedido', 'state')
    # ### end Alembic commands ###
