"""Migracao inicial

Revision ID: 49fcf427f0d4
Revises: 
Create Date: 2020-11-02 16:38:59.231268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49fcf427f0d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franquia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(length=19), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_franquia_eid'), 'franquia', ['eid'], unique=True)
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_permissao_eid'), 'permissao', ['eid'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('franquia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['franquia_id'], ['franquia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_usuario_eid'), 'usuario', ['eid'], unique=True)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('produto_slug', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('nome_completo', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone_celular', sa.String(length=14), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_eid'), 'pedido', ['eid'], unique=True)
    op.create_table('usuario_permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('permissao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('dados_produto', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_produto_eid'), 'pedido_produto', ['eid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_produto_eid'), table_name='pedido_produto')
    op.drop_table('pedido_produto')
    op.drop_table('usuario_permissao')
    op.drop_index(op.f('ix_pedido_eid'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_eid'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_permissao_eid'), table_name='permissao')
    op.drop_table('permissao')
    op.drop_index(op.f('ix_franquia_eid'), table_name='franquia')
    op.drop_table('franquia')
    # ### end Alembic commands ###
