"""BaseTable not nullable

Revision ID: c64c49f761cd
Revises: 1f654040949b
Create Date: 2020-04-18 18:58:02.178869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c64c49f761cd'
down_revision = '1f654040949b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pedido', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    op.alter_column('pedido', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pedido_produto', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pedido_produto', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    op.alter_column('pedido_produto', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('permissao', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('permissao', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    op.alter_column('permissao', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('usuario', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    op.alter_column('usuario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('usuario', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissao', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissao', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('permissao', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pedido_produto', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pedido_produto', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('pedido_produto', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pedido', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pedido', 'eid',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('pedido', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
